/*==============================================================================
  DECOMPOSITION TABLES

  Purpose:
    Generate two LaTeX tables summarising the counterfactual decomposition:
      1. Table: decomposition_summary.tex — overall summary
      2. Table: decomposition_by_year.tex — year-by-year appendix table

  Inputs:
    - ${work}/cfps_couples_earnings_power_pooled.dta   (reality)
    - ${work}/cfps_counterfactual_1_age_channel.dta     (CF1)
    - ${work}/cfps_counterfactual_2_wage_gap.dta        (CF2)
    - ${work}/cfps_counterfactual_3_both.dta            (CF3)

  Prerequisites: Run master.do first (sets global paths).
==============================================================================*/

clear all
set more off
set maxvar 10000


* ============================================================================
* 1.  COMPUTE OVERALL SUMMARY STATISTICS
* ============================================================================

* --- Reality ---
use "${work}/cfps_couples_earnings_power_pooled.dta", clear
sum diff_yp
local r_mean   = r(mean)
local r_N      = r(N)
sum hypergamy_yp
local r_hyper  = r(mean) * 100
sum homogamy_yp
local r_homo   = r(mean) * 100
sum hypogamy_yp
local r_hypo   = r(mean) * 100

* --- CF1 (age channel) ---
use "${work}/cfps_counterfactual_1_age_channel.dta", clear
sum diff_yp_cf
local cf1_mean  = r(mean)
local cf1_N     = r(N)
sum hypergamy_cf
local cf1_hyper = r(mean) * 100
sum homogamy_cf
local cf1_homo  = r(mean) * 100
sum hypogamy_cf
local cf1_hypo  = r(mean) * 100

* --- CF2 (wage gap) ---
use "${work}/cfps_counterfactual_2_wage_gap.dta", clear
sum diff_yp_cf
local cf2_mean  = r(mean)
local cf2_N     = r(N)
sum hypergamy_cf
local cf2_hyper = r(mean) * 100
sum homogamy_cf
local cf2_homo  = r(mean) * 100
sum hypogamy_cf
local cf2_hypo  = r(mean) * 100

* --- CF3 (both) ---
use "${work}/cfps_counterfactual_3_both.dta", clear
sum diff_yp_cf
local cf3_mean  = r(mean)
local cf3_N     = r(N)
sum hypergamy_cf
local cf3_hyper = r(mean) * 100
sum homogamy_cf
local cf3_homo  = r(mean) * 100
sum hypogamy_cf
local cf3_hypo  = r(mean) * 100

* --- Compute effects and shares ---
local cf1_effect = `cf1_mean' - `r_mean'
local cf2_effect = `cf2_mean' - `r_mean'
local cf3_effect = `cf3_mean' - `r_mean'
local interaction = `cf3_effect' - `cf1_effect' - `cf2_effect'

* Share of CF3 effect attributable to each channel
local cf1_share = (`cf1_effect' / `cf3_effect') * 100
local cf2_share = (`cf2_effect' / `cf3_effect') * 100


* ============================================================================
* 2.  WRITE SUMMARY TABLE (decomposition_summary.tex)
* ============================================================================

capture file close ftab
file open ftab using "${output}/decomposition_summary.tex", write replace

file write ftab "% Auto-generated by decomposition_tables.do" _n
file write ftab "% Do not edit by hand — re-run the do file to update." _n _n

file write ftab "\begin{table}[htbp]" _n
file write ftab "\centering" _n
file write ftab "\caption{Summary of Counterfactual Decomposition}" _n
file write ftab "\label{tab:decomposition_summary}" _n
file write ftab "\begin{tabular}{lcccc}" _n
file write ftab "\toprule" _n
file write ftab " & Reality & CF1: Age & CF2: Wage Gap & CF3: Both \\" _n
file write ftab "\midrule" _n

* Row: N
file write ftab "\quad Observations"
file write ftab " & " %12.0fc (`r_N')
file write ftab " & " %12.0fc (`cf1_N')
file write ftab " & " %12.0fc (`cf2_N')
file write ftab " & " %12.0fc (`cf3_N')
file write ftab " \\" _n

file write ftab "\addlinespace" _n

* Row: Mean gap
file write ftab "\quad Mean gap (wife $-$ husband, yuan/yr)"
file write ftab " & " %12.0fc (`r_mean')
file write ftab " & " %12.0fc (`cf1_mean')
file write ftab " & " %12.0fc (`cf2_mean')
file write ftab " & " %12.0fc (`cf3_mean')
file write ftab " \\" _n

* Row: Shift from reality
file write ftab "\quad Shift from reality"
file write ftab " & ---"
file write ftab " & $+" %12.0fc (`cf1_effect') "$"
file write ftab " & $+" %12.0fc (`cf2_effect') "$"
file write ftab " & $+" %12.0fc (`cf3_effect') "$"
file write ftab " \\" _n

* Row: Share of CF3 effect
file write ftab "\quad Share of CF3 effect (\%)"
file write ftab " & ---"
file write ftab " & " %5.1f (`cf1_share')
file write ftab " & " %5.1f (`cf2_share')
file write ftab " & 100.0"
file write ftab " \\" _n

file write ftab "\addlinespace" _n
file write ftab "\multicolumn{5}{l}{\textit{Categorical distribution (\%):}} \\" _n

* Row: Hypergamy
file write ftab "\quad Hypergamy"
file write ftab " & " %5.1f (`r_hyper')
file write ftab " & " %5.1f (`cf1_hyper')
file write ftab " & " %5.1f (`cf2_hyper')
file write ftab " & " %5.1f (`cf3_hyper')
file write ftab " \\" _n

* Row: Homogamy
file write ftab "\quad Homogamy"
file write ftab " & " %5.1f (`r_homo')
file write ftab " & " %5.1f (`cf1_homo')
file write ftab " & " %5.1f (`cf2_homo')
file write ftab " & " %5.1f (`cf3_homo')
file write ftab " \\" _n

* Row: Hypogamy
file write ftab "\quad Hypogamy"
file write ftab " & " %5.1f (`r_hypo')
file write ftab " & " %5.1f (`cf1_hypo')
file write ftab " & " %5.1f (`cf2_hypo')
file write ftab " & " %5.1f (`cf3_hypo')
file write ftab " \\" _n

file write ftab "\addlinespace" _n

* Row: Interaction
file write ftab "\quad Interaction (CF3 $-$ CF1 $-$ CF2)"
file write ftab " & ---"
file write ftab " & \multicolumn{3}{c}{" %12.0fc (`interaction') " yuan/yr}"
file write ftab " \\" _n

file write ftab "\bottomrule" _n
file write ftab "\end{tabular}" _n

file write ftab "\smallskip" _n
file write ftab "{\footnotesize \textit{Notes}: " _n
file write ftab "Mean gap is wife's permanent income minus husband's (negative = husband earns more). " _n
file write ftab "CF1 equalises age at marriage; CF2 equalises Mincerian coefficients; CF3 equalises both. " _n
file write ftab "Homogamy defined as $|\hat{Y}_w - \hat{Y}_h| / [(\hat{Y}_w + \hat{Y}_h)/2] < 5\%$. " _n
file write ftab "Shift = counterfactual mean gap minus reality mean gap. " _n
file write ftab "Interaction = CF3 shift $-$ (CF1 shift $+$ CF2 shift).}" _n

file write ftab "\end{table}" _n

file close ftab

di _n "Summary table saved to: ${output}/decomposition_summary.tex"


* ============================================================================
* 3.  COMPUTE YEAR-BY-YEAR STATISTICS
* ============================================================================

* --- Reality by year ---
use "${work}/cfps_couples_earnings_power_pooled.dta", clear
collapse (mean) r_mean=diff_yp r_hyper=hypergamy_yp r_homo=homogamy_yp ///
         r_hypo=hypogamy_yp ///
         (count) r_N=diff_yp, ///
    by(marry_year)
tempfile reality_yr
save `reality_yr'

* --- CF1 by year ---
use "${work}/cfps_counterfactual_1_age_channel.dta", clear
collapse (mean) cf1_mean=diff_yp_cf cf1_hyper=hypergamy_cf cf1_homo=homogamy_cf ///
         cf1_hypo=hypogamy_cf ///
         (count) cf1_N=diff_yp_cf, ///
    by(marry_year)
tempfile cf1_yr
save `cf1_yr'

* --- CF2 by year ---
use "${work}/cfps_counterfactual_2_wage_gap.dta", clear
collapse (mean) cf2_mean=diff_yp_cf cf2_hyper=hypergamy_cf cf2_homo=homogamy_cf ///
         cf2_hypo=hypogamy_cf ///
         (count) cf2_N=diff_yp_cf, ///
    by(marry_year)
tempfile cf2_yr
save `cf2_yr'

* --- CF3 by year ---
use "${work}/cfps_counterfactual_3_both.dta", clear
collapse (mean) cf3_mean=diff_yp_cf cf3_hyper=hypergamy_cf cf3_homo=homogamy_cf ///
         cf3_hypo=hypogamy_cf ///
         (count) cf3_N=diff_yp_cf, ///
    by(marry_year)
tempfile cf3_yr
save `cf3_yr'

* --- Merge all ---
use `reality_yr', clear
merge 1:1 marry_year using `cf1_yr',  nogen
merge 1:1 marry_year using `cf2_yr',  nogen
merge 1:1 marry_year using `cf3_yr',  nogen

* Convert shares to percentages
foreach v in r_hyper r_homo r_hypo cf1_hyper cf1_homo cf1_hypo ///
             cf2_hyper cf2_homo cf2_hypo cf3_hyper cf3_homo cf3_hypo {
    replace `v' = `v' * 100
}

* Compute effects
gen cf1_effect = cf1_mean - r_mean
gen cf2_effect = cf2_mean - r_mean
gen cf3_effect = cf3_mean - r_mean
gen interaction = cf3_effect - cf1_effect - cf2_effect

sort marry_year
list, separator(0) noobs


* ============================================================================
* 4.  WRITE YEAR-BY-YEAR TABLE (decomposition_by_year.tex)
* ============================================================================

capture file close ftab
file open ftab using "${output}/decomposition_by_year.tex", write replace

file write ftab "% Auto-generated by decomposition_tables.do" _n
file write ftab "% Do not edit by hand — re-run the do file to update." _n _n

file write ftab "\begin{table}[htbp]" _n
file write ftab "\centering" _n
file write ftab "\caption{Counterfactual Decomposition by Marriage Year}" _n
file write ftab "\label{tab:decomposition_by_year}" _n
file write ftab "\footnotesize" _n
file write ftab "\begin{tabular}{l*{11}{c}}" _n
file write ftab "\toprule" _n
file write ftab " & 2010 & 2011 & 2012 & 2013 & 2014 & 2015 & 2016 & 2017 & 2018 & 2019 & 2020 \\" _n
file write ftab "\midrule" _n

* --- Panel A: Mean gap ---
file write ftab "\multicolumn{12}{l}{\textit{Panel A: Mean wife--husband permanent income gap (yuan/yr)}} \\" _n

* Reality row
file write ftab "\quad Reality"
local N = _N
forvalues i = 1/`N' {
    local v = r_mean[`i']
    file write ftab " & " %7.0fc (`v')
}
file write ftab " \\" _n

* CF1 row
file write ftab "\quad CF1: Age"
forvalues i = 1/`N' {
    local v = cf1_mean[`i']
    file write ftab " & " %7.0fc (`v')
}
file write ftab " \\" _n

* CF2 row
file write ftab "\quad CF2: Wage gap"
forvalues i = 1/`N' {
    local v = cf2_mean[`i']
    file write ftab " & " %7.0fc (`v')
}
file write ftab " \\" _n

* CF3 row
file write ftab "\quad CF3: Both"
forvalues i = 1/`N' {
    local v = cf3_mean[`i']
    file write ftab " & " %7.0fc (`v')
}
file write ftab " \\" _n

file write ftab "\addlinespace" _n

* --- Panel B: Shifts ---
file write ftab "\multicolumn{12}{l}{\textit{Panel B: Shift from reality (yuan/yr)}} \\" _n

file write ftab "\quad CF1: Age"
forvalues i = 1/`N' {
    local v = cf1_effect[`i']
    file write ftab " & " %7.0fc (`v')
}
file write ftab " \\" _n

file write ftab "\quad CF2: Wage gap"
forvalues i = 1/`N' {
    local v = cf2_effect[`i']
    file write ftab " & " %7.0fc (`v')
}
file write ftab " \\" _n

file write ftab "\quad CF3: Both"
forvalues i = 1/`N' {
    local v = cf3_effect[`i']
    file write ftab " & " %7.0fc (`v')
}
file write ftab " \\" _n

file write ftab "\quad Interaction"
forvalues i = 1/`N' {
    local v = interaction[`i']
    file write ftab " & " %7.0fc (`v')
}
file write ftab " \\" _n

file write ftab "\addlinespace" _n

* --- Panel C: Hypergamy rate ---
file write ftab "\multicolumn{12}{l}{\textit{Panel C: Hypergamy rate (\%)}} \\" _n

file write ftab "\quad Reality"
forvalues i = 1/`N' {
    local v = r_hyper[`i']
    file write ftab " & " %5.1f (`v')
}
file write ftab " \\" _n

file write ftab "\quad CF1: Age"
forvalues i = 1/`N' {
    local v = cf1_hyper[`i']
    file write ftab " & " %5.1f (`v')
}
file write ftab " \\" _n

file write ftab "\quad CF2: Wage gap"
forvalues i = 1/`N' {
    local v = cf2_hyper[`i']
    file write ftab " & " %5.1f (`v')
}
file write ftab " \\" _n

file write ftab "\quad CF3: Both"
forvalues i = 1/`N' {
    local v = cf3_hyper[`i']
    file write ftab " & " %5.1f (`v')
}
file write ftab " \\" _n

file write ftab "\addlinespace" _n

* --- Panel D: Homogamy rate ---
file write ftab "\multicolumn{12}{l}{\textit{Panel D: Homogamy rate (\%)}} \\" _n

file write ftab "\quad Reality"
forvalues i = 1/`N' {
    local v = r_homo[`i']
    file write ftab " & " %5.1f (`v')
}
file write ftab " \\" _n

file write ftab "\quad CF1: Age"
forvalues i = 1/`N' {
    local v = cf1_homo[`i']
    file write ftab " & " %5.1f (`v')
}
file write ftab " \\" _n

file write ftab "\quad CF2: Wage gap"
forvalues i = 1/`N' {
    local v = cf2_homo[`i']
    file write ftab " & " %5.1f (`v')
}
file write ftab " \\" _n

file write ftab "\quad CF3: Both"
forvalues i = 1/`N' {
    local v = cf3_homo[`i']
    file write ftab " & " %5.1f (`v')
}
file write ftab " \\" _n

file write ftab "\addlinespace" _n

* --- Panel E: Hypogamy rate ---
file write ftab "\multicolumn{12}{l}{\textit{Panel E: Hypogamy rate (\%)}} \\" _n

file write ftab "\quad Reality"
forvalues i = 1/`N' {
    local v = r_hypo[`i']
    file write ftab " & " %5.1f (`v')
}
file write ftab " \\" _n

file write ftab "\quad CF1: Age"
forvalues i = 1/`N' {
    local v = cf1_hypo[`i']
    file write ftab " & " %5.1f (`v')
}
file write ftab " \\" _n

file write ftab "\quad CF2: Wage gap"
forvalues i = 1/`N' {
    local v = cf2_hypo[`i']
    file write ftab " & " %5.1f (`v')
}
file write ftab " \\" _n

file write ftab "\quad CF3: Both"
forvalues i = 1/`N' {
    local v = cf3_hypo[`i']
    file write ftab " & " %5.1f (`v')
}
file write ftab " \\" _n

file write ftab "\addlinespace" _n

* --- Panel F: N ---
file write ftab "\multicolumn{12}{l}{\textit{Panel F: Number of couples}} \\" _n

file write ftab "\quad $N$"
forvalues i = 1/`N' {
    local v = r_N[`i']
    file write ftab " & " %5.0fc (`v')
}
file write ftab " \\" _n

file write ftab "\bottomrule" _n
file write ftab "\end{tabular}" _n

file write ftab "\smallskip" _n
file write ftab "{\footnotesize \textit{Notes}: " _n
file write ftab "Mean gap is wife's permanent income minus husband's (negative = husband earns more). " _n
file write ftab "CF1 equalises age at marriage; CF2 equalises Mincerian coefficients; CF3 equalises both. " _n
file write ftab "Homogamy defined as $|\hat{Y}_w - \hat{Y}_h| / [(\hat{Y}_w + \hat{Y}_h)/2] < 5\%$. " _n
file write ftab "Shift = counterfactual mean gap minus reality mean gap. " _n
file write ftab "Interaction = CF3 shift $-$ (CF1 shift $+$ CF2 shift).}" _n

file write ftab "\end{table}" _n

file close ftab

di _n "Year-by-year table saved to: ${output}/decomposition_by_year.tex"


* ============================================================================
* 5.  DONE
* ============================================================================

di _n "================================================================="
di    "DONE — Decomposition Tables"
di    "  ${output}/decomposition_summary.tex"
di    "  ${output}/decomposition_by_year.tex"
di    "================================================================="
